# Generated by Django 2.0 on 2018-08-12 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createclub', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movieclub',
            name='slug',
            field=models.SlugField(default='default_slug', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movieclub',
            name='privacy',
            field=models.CharField(choices=[('private', 'Private'), ('public', 'Public')], max_length=7),
        ),
    ]
